### PR TITLE
image pasting restoration for media alpha 4 - Update ucsf_webedit.features.filter.inc

### PR DESCRIPTION
**Pull request by erykmynn**
adding data-fid to IMG allowed paste for webedit-paste to restore pasting of media-based images.

### CODE REVIEW

**Comment by erykmynn** [comment]
not sure if it needs a FR - will test

**Comment by erykmynn** [comment]
references #27

**Comment by erykmynn** [comment]
appears to only need a CC ALL

**Comment by Quevin** [comment]
I've verified this fix locally, and a "cc all" was only required (didn't have to "drush fr"). Tested by cut/paste, viewed code to see media token... saved after testing a few times and image remains.

**Pull request merged**
